platform :ios, '11'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
#use_modular_headers!

# XXFramework 依赖
def XXFramework_libs()
    pod 'SDWebImage', '~> 5.0'
end

target '刻画' do
    XXFramework_libs()
end
